Repository apache/skywalking-java, pull requests merged in 2021-11, with the labels that each got.

#64 Fix release doc about docker images
  docs/en/contribution/release-java-agent.md
Labels: documentation

#60 [Enhance]For trace CompletableFuture thenApply or thenAccept
  CHANGES.md
  apm-application-toolkit/apm-toolkit-trace/src/main/java/org/apache/skywalking/apm/toolkit/trace/ConsumerWrapper.java
  apm-application-toolkit/apm-toolkit-trace/src/main/java/org/apache/skywalking/apm/toolkit/trace/FunctionWrapper.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-trace-activation/src/main/java/org/apache/skywalking/apm/toolkit/activation/trace/CallableOrRunnableActivation.java
  docs/en/setup/service-agent/java-agent/Application-toolkit-trace-cross-thread.md
  test/plugin/scenarios/apm-toolkit-trace-scenario/config/expectedData.yaml
  test/plugin/scenarios/apm-toolkit-trace-scenario/src/main/java/org/apache/skywalking/apm/toolkit/trace/ConsumerWrapper.java
  test/plugin/scenarios/apm-toolkit-trace-scenario/src/main/java/org/apache/skywalking/apm/toolkit/trace/FunctionWrapper.java
  test/plugin/scenarios/apm-toolkit-trace-scenario/src/main/java/test/apache/skywalking/apm/testcase/toolkit/controller/TestController.java
  test/plugin/scenarios/apm-toolkit-trace-scenario/src/main/java/test/apache/skywalking/apm/testcase/toolkit/controller/TestService.java
Labels: enhancement, plugin

#65 Build CLI from Docker instead of source codes, add alpine and jdk17 based Docker image
  .github/workflows/publish-docker.yaml
  CHANGES.md
  Dockerfile
  Makefile
  docs/en/contribution/compiling.md
  docs/en/contribution/release-java-agent.md
Labels: chore, docker

#66 add Pulsar Reporter docs link
  docs/en/setup/service-agent/java-agent/advanced-reporters.md
Labels: documentation

#67 Support set instance properties in json format
  CHANGES.md
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/Config.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/remote/ServiceManagementClient.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/util/InstanceJsonPropertiesUtil.java
  apm-sniffer/config/agent.config
  apm-sniffer/optional-reporter-plugins/kafka-reporter-plugin/src/main/java/org/apache/skywalking/apm/agent/core/kafka/KafkaServiceManagementServiceClient.java
  docs/en/setup/service-agent/java-agent/configurations.md
  test/e2e/base/base-compose.yml
  test/e2e/case/expected/service-instance.yml
Labels: feature

#68 Correct asynchttpclient-scenario case and supported versions.
  docs/en/setup/service-agent/java-agent/Supported-list.md
  test/plugin/scenarios/asynchttpclient-scenario/pom.xml
  test/plugin/scenarios/asynchttpclient-scenario/support-version.list
Labels: testing

#69 Fix wrong dependency in doc for IgnoredException
  docs/en/setup/service-agent/java-agent/How-to-tolerate-exceptions.md
Labels: documentation

#70 Add rocketmq reporter link to doc
  docs/en/setup/service-agent/java-agent/advanced-reporters.md
Labels: documentation

#74 Upgrade grpc-java to 1.42.1 and protoc to 3.19.1 to allow using native Mac osx-aarch_64 artifacts
  CHANGES.md
  dist-material/LICENSE
  pom.xml
Labels: dependency

#75 Correct the CHANGELOG about gRPC version
  CHANGES.md
Labels: documentation
