Repository apache/skywalking-java, pull requests merged in 2022-03, with the labels that each got.

#113 Add witness classes to graphql and vertx-core-3.x plugins
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/graphql-plugin/graphql-12.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/graphql/v12/define/GraphqlInstrumentation.java
  apm-sniffer/apm-sdk-plugin/graphql-plugin/graphql-8.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/graphql/v8/define/GraphqlInstrumentation.java
  apm-sniffer/apm-sdk-plugin/graphql-plugin/graphql-9.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/graphql/v9/define/GraphqlInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/ClusteredEventBusSendRemoteInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/EventBusImplDeliverToHandlerInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/HandlerRegistrationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/HttpClientRequestImplHandleExceptionInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/HttpClientRequestImplHandleResponseInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/HttpClientRequestImplInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/HttpContextHandleDispatchResponseInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/HttpContextSendRequestInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/HttpServerRequestImplConstructorInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/HttpServerRequestWrapperConstructorInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/HttpServerResponseImplHandleExceptionInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/HttpServerResponseImplInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/RouteImplHandlerInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/RouteImplInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/RouteStateInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/RouterContextImplBaseConstructorInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/RoutingContextWrapperConstructorInstrumentation.java
  apm-sniffer/apm-sdk-plugin/vertx-plugins/vertx-core-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/vertx3/define/ServerConnectionHandleMessageInstrumentation.java
Labels: enhancement

#120 Renamed graphql-12.x-plugin to graphql-12.x-15.x-plugin
  .github/workflows/plugins-test.3.yaml
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/graphql-plugin/graphql-12.x-15.x-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/graphql-plugin/graphql-12.x-15.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/graphql/v12tov15/GraphqlInterceptor.java
  apm-sniffer/apm-sdk-plugin/graphql-plugin/graphql-12.x-15.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/graphql/v12tov15/define/GraphqlInstrumentation.java
  apm-sniffer/apm-sdk-plugin/graphql-plugin/graphql-12.x-15.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/apm-sdk-plugin/graphql-plugin/graphql-8.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/apm-sdk-plugin/graphql-plugin/graphql-9.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/apm-sdk-plugin/graphql-plugin/pom.xml
  docs/en/setup/service-agent/java-agent/Plugin-list.md
  test/plugin/scenarios/graphql-12.x-15.x-scenario/bin/startup.sh
  test/plugin/scenarios/graphql-12.x-15.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/graphql-12.x-15.x-scenario/configuration.yml
  test/plugin/scenarios/graphql-12.x-15.x-scenario/pom.xml
  test/plugin/scenarios/graphql-12.x-15.x-scenario/src/main/assembly/assembly.xml
  test/plugin/scenarios/graphql-12.x-15.x-scenario/src/main/java/org/apache/skywalking/apm/testcase/graphql/Application.java
  test/plugin/scenarios/graphql-12.x-15.x-scenario/src/main/java/org/apache/skywalking/apm/testcase/graphql/configuration/GraphSchema.java
  test/plugin/scenarios/graphql-12.x-15.x-scenario/src/main/java/org/apache/skywalking/apm/testcase/graphql/controller/CaseController.java
  test/plugin/scenarios/graphql-12.x-15.x-scenario/src/main/java/org/apache/skywalking/apm/testcase/graphql/data/User.java
  test/plugin/scenarios/graphql-12.x-15.x-scenario/src/main/resources/application.yml
  test/plugin/scenarios/graphql-12.x-15.x-scenario/support-version.list
Labels: enhancement, plugin

#122 test: support to the custom base image by configuration
  .github/actions/build/action.yml
  .github/actions/run/action.yml
  .github/workflows/plugins-jdk14-test.0.yaml
  .github/workflows/plugins-jdk17-test.0.yaml
  CHANGES.md
  docs/en/setup/service-agent/java-agent/Plugin-test.md
  test/plugin/containers/jvm-container/pom.xml
  test/plugin/containers/tomcat-container/pom.xml
  test/plugin/run.sh
Labels: testing

#123 Add cluster concept to the configuration, and enhance namespace concept
  CHANGES.md
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/Config.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/Constants.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/SnifferConfigInitializer.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/CarrierItem.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/TracingContext.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/util/InstanceJsonPropertiesUtil.java
  apm-sniffer/apm-agent-core/src/test/java/org/apache/skywalking/apm/agent/core/conf/SnifferConfigInitializerTest.java
  apm-sniffer/config/agent.config
  docs/en/setup/service-agent/java-agent/configurations.md
Labels: enhancement, core

#125 Clean doc of previous namespace
  docs/en/setup/service-agent/java-agent/Namespace.md
  docs/en/setup/service-agent/java-agent/advanced-features.md
  docs/menu.yml
Labels: documentation

#128 Make sure Tomcat thread plugin working in Tomcat 9
  apm-sniffer/apm-sdk-plugin/tomcat-thread-pool-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/tomcat-thread-pool-plugin/src/main/java/org/apache/skywalking/apm/plugin/tomcat/thread/pool/TomcatThreadExecutorInterceptor.java
  test/plugin/scenarios/h2-scenario/config/expectedData.yaml
  test/plugin/scenarios/h2-scenario/configuration.yml
  test/plugin/scenarios/h2-scenario/pom.xml
Labels: bug, plugin

#129 Make sure the parent endpoint from existing first ENTRY span
  CHANGES.md
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/TracingContext.java
Labels: bug, core

#130 Remove unnecessary InterruptedException catch
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/commands/CommandService.java
Labels: chore, TBD

#131 Pin dead-link-checker to fixed version
  .github/workflows/dead-link-checker.yaml
Labels: CI Setting
