Repository apache/skywalking-java, pull requests merged in 2022-01, with the labels that each got.

#87 Update year to 2022.
  NOTICE
  dist-material/NOTICE
Labels: chore

#88 Compatible with the versions after dubbo-2.7.14
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/dubbo-2.7.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/asf/dubbo/DubboInterceptor.java
  test/plugin/scenarios/dubbo-2.7.x-scenario/support-version.list
Labels: bug

#91 Feature/redis plugins config
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/jedis-2.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jedis/v2/JedisMethodInterceptor.java
  apm-sniffer/apm-sdk-plugin/jedis-2.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jedis/v2/JedisPluginConfig.java
  apm-sniffer/apm-sdk-plugin/jedis-2.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jedis/v2/JedisMethodInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/redisson-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/redisson/v3/RedisConnectionMethodInterceptor.java
  apm-sniffer/apm-sdk-plugin/redisson-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/redisson/v3/RedissonPluginConfig.java
  docs/en/setup/service-agent/java-agent/configurations.md
  test/plugin/scenarios/jedis-scenario/bin/startup.sh
  test/plugin/scenarios/redisson-scenario/bin/startup.sh
Labels: enhancement, plugin

#94 Remove mesos from readme
  README.md
Labels: documentation

#97 Migrate base images to Temurin and add images for ARM
  .github/workflows/publish-docker.yaml
  CHANGES.md
  Dockerfile
  Makefile
  docs/en/contribution/compiling.md
  test/e2e/base/base-compose.yml
  test/e2e/base/consumer/Dockerfile
  test/e2e/base/provider/Dockerfile
  test/e2e/case/kafka/e2e.yaml
Labels: docker

#100 Bump up gRPC to 1.44.0, fix relative CVEs.
  CHANGES.md
  dist-material/LICENSE
  pom.xml
Labels: dependency

#95 Support thread pool metric collect
  .github/workflows/plugins-test.3.yaml
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/undertow-worker-thread-pool-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/undertow-worker-thread-pool-plugin/src/main/java/org/apache/skywalking/apm/plugin/undertow/worker/thread/pool/UndertowWorkerThreadPoolConstructorIntercept.java
  apm-sniffer/apm-sdk-plugin/undertow-worker-thread-pool-plugin/src/main/java/org/apache/skywalking/apm/plugin/undertow/worker/thread/pool/define/UndertowWorkerThreadPoolInstrumentation.java
  apm-sniffer/apm-sdk-plugin/undertow-worker-thread-pool-plugin/src/main/resources/skywalking-plugin.def
  docs/en/setup/service-agent/java-agent/Plugin-list.md
  docs/en/setup/service-agent/java-agent/Supported-list.md
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/bin/startup.sh
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/config/expectedData.yaml
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/configuration.yml
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/pom.xml
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/src/main/assembly/assembly.xml
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/src/main/java/org/apache/skywalking/apm/testcase/undertowworkerthreadpool/Application.java
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/src/main/java/org/apache/skywalking/apm/testcase/undertowworkerthreadpool/controller/CaseController.java
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/src/main/resources/application.yaml
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/src/main/resources/log4j2.xml
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/support-version.list
Labels: enhancement, plugin

#102 Fix comment in ZGC
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/jvm/gc/GCProvider.java
Labels: chore

#103 Fix change logs
  CHANGES.md
Labels: chore

#104 Fix typo
  CHANGES.md
Labels: chore
