Repository apache/skywalking-java, pull requests merged in 2022-12, with the labels that each got.

#402 Add micronauthttpclient,micronauthttpserver,memcached,ehcache,guavacache,jedis,redisson plugin config properties to agent.config
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/jedis-plugins/jedis-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jedis/v4/AbstractConnectionInterceptor.java
  apm-sniffer/apm-sdk-plugin/jedis-plugins/jedis-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jedis/v4/JedisPluginConfig.java
  apm-sniffer/config/agent.config
  docs/en/setup/service-agent/java-agent/configurations.md
  test/plugin/scenarios/jedis-4.x-scenario/config/expectedData.yaml
Labels: documentation, enhancement, plugin

#404 Add tags `mq.message.keys` and `mq.message.tags` for RocketMQ producer span
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/rocketMQ-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rocketMQ/v3/MessageSendInterceptor.java
  apm-sniffer/apm-sdk-plugin/rocketMQ-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rocketMQ/v4/MessageSendInterceptor.java
  test/plugin/scenarios/rocketmq-scenario/config/expectedData.yaml
  test/plugin/scenarios/rocketmq-scenario/pom.xml
  test/plugin/scenarios/rocketmq-scenario/src/main/java/test/apache/skywalking/apm/testcase/rocketmq/controller/CaseController.java
Labels: enhancement, plugin

#403 Fix flaky test caused by .toArray()
  apm-commons/apm-util/src/test/java/org/apache/skywalking/apm/util/ConfigInitializerTest.java
Labels: chore, testing

#401 Adds Micrometer Observation instrumentation
  .github/workflows/plugins-jdk17-test.0.yaml
  CHANGES.md
  apm-application-toolkit/apm-toolkit-micrometer-1.10/pom.xml
  apm-application-toolkit/apm-toolkit-micrometer-1.10/src/main/java/org/apache/skywalking/apm/toolkit/micrometer/observation/SkywalkingContextSnapshotThreadLocalAccessor.java
  apm-application-toolkit/apm-toolkit-micrometer-1.10/src/main/java/org/apache/skywalking/apm/toolkit/micrometer/observation/SkywalkingDefaultTracingHandler.java
  apm-application-toolkit/apm-toolkit-micrometer-1.10/src/main/java/org/apache/skywalking/apm/toolkit/micrometer/observation/SkywalkingMeterHandler.java
  apm-application-toolkit/apm-toolkit-micrometer-1.10/src/main/java/org/apache/skywalking/apm/toolkit/micrometer/observation/SkywalkingReceiverTracingHandler.java
  apm-application-toolkit/apm-toolkit-micrometer-1.10/src/main/java/org/apache/skywalking/apm/toolkit/micrometer/observation/SkywalkingSenderTracingHandler.java
  apm-application-toolkit/apm-toolkit-micrometer-1.10/src/main/resources/META-INF/services/io.micrometer.context.ThreadLocalAccessor
  apm-application-toolkit/apm-toolkit-micrometer-1.10/src/test/java/org/apache/skywalking/apm/toolkit/micrometer/observation/SkywalkingMeterHandlerTests.java
  apm-application-toolkit/pom.xml
  apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/ComponentsDefine.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/pom.xml
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/main/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerContextManagerThreadLocalAccessorInstrumentation.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/main/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerContextSnapshotThreadLocalAccessorInterceptor.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/main/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerDefaultTracingHandlerInstrumentation.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/main/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerDefaultTracingHandlerInterceptor.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/main/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerReceiverTracingHandlerInstrumentation.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/main/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerReceiverTracingHandlerInterceptor.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/main/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerSenderTracingHandlerInstrumentation.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/main/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerSenderTracingHandlerInterceptor.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/main/java/org/apache/skywalking/apm/toolkit/activation/micrometer/SpanHelper.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/main/java/org/apache/skywalking/apm/toolkit/activation/micrometer/TaggingHelper.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/main/resources/skywalking-plugin.def
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/test/java/org/apache/skywalking/apm/toolkit/activation/micrometer/AbstractTracingSpanHelper.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/test/java/org/apache/skywalking/apm/toolkit/activation/micrometer/ContextManagerExtendOverrideService.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/test/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerContextSnapshotThreadLocalAccessorInterceptorTest.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/test/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerDefaultTracingHandlerInterceptorTest.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/test/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerReceiverTracingHandlerInterceptorTest.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/test/java/org/apache/skywalking/apm/toolkit/activation/micrometer/MicrometerSenderTracingHandlerInterceptorTest.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/test/java/org/apache/skywalking/apm/toolkit/activation/micrometer/PluginBootService.java
  apm-sniffer/apm-toolkit-activation/apm-toolkit-micrometer-activation/src/test/resources/META-INF/services/org.apache.skywalking.apm.agent.core.boot.BootService
  apm-sniffer/apm-toolkit-activation/pom.xml
  docs/en/setup/service-agent/java-agent/Application-toolkit-micrometer-1.10.md
  docs/en/setup/service-agent/java-agent/Application-toolkit-micrometer.md
  docs/en/setup/service-agent/java-agent/Plugin-list.md
  docs/en/setup/service-agent/java-agent/advanced-features.md
  docs/menu.yml
  pom.xml
  test/plugin/agent-test-tools/pom.xml
  test/plugin/containers/tomcat-container/src/main/docker/run.sh
  test/plugin/run.sh
  test/plugin/scenarios/resttemplate-6.x-scenario/bin/startup.sh
  test/plugin/scenarios/resttemplate-6.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/resttemplate-6.x-scenario/configuration.yml
  test/plugin/scenarios/resttemplate-6.x-scenario/pom.xml
  test/plugin/scenarios/resttemplate-6.x-scenario/src/main/assembly/assembly.xml
  test/plugin/scenarios/resttemplate-6.x-scenario/src/main/java/org/apache/skywalking/testcase/resttemplate/BackController.java
  test/plugin/scenarios/resttemplate-6.x-scenario/src/main/java/org/apache/skywalking/testcase/resttemplate/FrontController.java
  test/plugin/scenarios/resttemplate-6.x-scenario/src/main/java/org/apache/skywalking/testcase/resttemplate/ObservationConfiguration.java
  test/plugin/scenarios/resttemplate-6.x-scenario/src/main/java/org/apache/skywalking/testcase/resttemplate/ResttemplateConfiguration.java
  test/plugin/scenarios/resttemplate-6.x-scenario/src/main/java/org/apache/skywalking/testcase/resttemplate/ServerConfiguration.java
  test/plugin/scenarios/resttemplate-6.x-scenario/src/main/java/org/apache/skywalking/testcase/resttemplate/SkywalkingApplication.java
  test/plugin/scenarios/resttemplate-6.x-scenario/src/main/resources/application.yml
  test/plugin/scenarios/resttemplate-6.x-scenario/src/main/resources/log4j2.xml
  test/plugin/scenarios/resttemplate-6.x-scenario/support-version.list
Labels: plugin

#405 [fix][plugin][pulsar] Clean message context after message is recycled to prevent memory leak.
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/main/java/org/apache/skywalking/apm/plugin/pulsar/common/MessageRecycleMethodInterceptor.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/main/java/org/apache/skywalking/apm/plugin/pulsar/common/define/BaseMessageInstrumentation.java
Labels: bug, plugin

#430 Suspend clickhouse plugin test for now
  .github/workflows/plugins-test.3.yaml
Labels: testing

#427 [fix] In the higher version of mysql-connector-java 8x, there is an error in the value of db.instance.
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/mysql-8.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/mysql/v8/define/ConnectionInstrumentation.java
Labels: bug, plugin

#429 Add kafka-clients 3.x support
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/kafka-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/Kafka3ConsumerInterceptor.java
  apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/KafkaConsumerInterceptor.java
  apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/define/KafkaConsumerInstrumentation.java
  docs/en/setup/service-agent/java-agent/Supported-list.md
  test/plugin/scenarios/kafka-scenario/support-version.list
Labels: enhancement

#432 Revert #430
  .github/workflows/plugins-test.3.yaml
Labels: testing

#428 Support to customize the collect period of JVM relative metrics.
  CHANGES.md
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/Config.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/jvm/JVMService.java
  apm-sniffer/config/agent.config
  docs/en/setup/service-agent/java-agent/configurations.md
Labels: enhancement

#434 fix CVE-2022-41915
  CHANGES.md
  dist-material/LICENSE
  pom.xml
Labels: dependency
