Repository apache/skywalking-java, pull requests merged in 2022-11, with the labels that each got.

#369 Add MQ_TOPIC and MQ_BROKER tags for RocketMQ consumer's span
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/rocketMQ-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rocketMQ/v4/AbstractMessageConsumeInterceptor.java
  apm-sniffer/apm-sdk-plugin/rocketMQ-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rocketMQ/v4/RegisterMessageListenerInterceptor.java
  apm-sniffer/apm-sdk-plugin/rocketMQ-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rocketMQ/v4/define/ConsumerEnhanceInfos.java
  apm-sniffer/apm-sdk-plugin/rocketMQ-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rocketMQ/v4/define/DefaultMQPushConsumerInstrumentation.java
  apm-sniffer/apm-sdk-plugin/rocketMQ-4.x-plugin/src/main/resources/skywalking-plugin.def
  test/plugin/scenarios/rocketmq-scenario/config/expectedData.yaml
Labels: plugin, feature

#374 Mention Virtual MQ support in the changelog
  CHANGES.md
  docs/en/setup/service-agent/java-agent/Java-Plugin-Development-Guide.md
Labels: chore

#375 Polish up pulsar plugins to remove unnecessary dynamic value , set peer at consumer side
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/pulsar-2.2-2.7-plugin/src/main/java/org/apache/skywalking/apm/plugin/pulsar/ProducerConstructorInterceptor.java
  apm-sniffer/apm-sdk-plugin/pulsar-2.2-2.7-plugin/src/test/java/org/apache/skywalking/apm/plugin/pulsar/MockMessage.java
  apm-sniffer/apm-sdk-plugin/pulsar-2.2-2.7-plugin/src/test/java/org/apache/skywalking/apm/plugin/pulsar/ProducerConstructorInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/pulsar-2.8.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/pulsar/v28x/ProducerConstructorInterceptor.java
  apm-sniffer/apm-sdk-plugin/pulsar-2.8.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/pulsar/v28x/ProducerConstructorInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/main/java/org/apache/skywalking/apm/plugin/pulsar/common/ConsumerConstructorInterceptor.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/main/java/org/apache/skywalking/apm/plugin/pulsar/common/ConsumerEnhanceRequiredInfo.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/main/java/org/apache/skywalking/apm/plugin/pulsar/common/ProducerEnhanceRequiredInfo.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/main/java/org/apache/skywalking/apm/plugin/pulsar/common/PulsarConsumerInterceptor.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/main/java/org/apache/skywalking/apm/plugin/pulsar/common/PulsarProducerInterceptor.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/test/java/org/apache/skywalking/apm/plugin/pulsar/common/ConsumerConstructorInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/test/java/org/apache/skywalking/apm/plugin/pulsar/common/MockConsumerImpl.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/test/java/org/apache/skywalking/apm/plugin/pulsar/common/MockProducerImpl.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/test/java/org/apache/skywalking/apm/plugin/pulsar/common/PulsarConsumerInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/test/java/org/apache/skywalking/apm/plugin/pulsar/common/PulsarConsumerListenerInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/pulsar-common/src/test/java/org/apache/skywalking/apm/plugin/pulsar/common/PulsarProducerInterceptorTest.java
  test/plugin/scenarios/pulsar-scenario/config/expectedData.yaml
Labels: enhancement, plugin

#377 Polish up kafka,nats,activemq,rabbitmq plugins to set peer at comsumer side
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/activemq-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/activemq/MessageConsumerDequeueInterceptor.java
  apm-sniffer/apm-sdk-plugin/kafka-plugin/src/main/java/org/apache/skywalking/apm/plugin/kafka/KafkaConsumerInterceptor.java
  apm-sniffer/apm-sdk-plugin/nats-2.14.x-2.15.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/nats/client/DeliverReplyInterceptor.java
  apm-sniffer/apm-sdk-plugin/nats-2.14.x-2.15.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/nats/client/NatsCommons.java
  apm-sniffer/apm-sdk-plugin/nats-2.14.x-2.15.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/nats/client/SubscriptionNextMsgInterceptor.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rabbitmq/TracerConsumer.java
  docs/en/setup/service-agent/java-agent/Java-Plugin-Development-Guide.md
  test/plugin/scenarios/activemq-scenario/config/expectedData.yaml
  test/plugin/scenarios/kafka-scenario/config/expectedData.yaml
  test/plugin/scenarios/nats-2.14.x-2.15.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/rabbitmq-scenario/config/expectedData.yaml
  test/plugin/scenarios/spring-kafka-1.3.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/spring-kafka-2.2.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/spring-kafka-2.3.x-scenario/config/expectedData.yaml
Labels: enhancement, plugin

#379 Basic testing support on arm64/v8 platforms
  .github/actions/build/action.yml
  .github/workflows/plugins-jdk17-test.0.yaml
  CHANGES.md
  docs/en/setup/service-agent/java-agent/Plugin-test.md
  test/plugin/containers/jvm-container/pom.xml
  test/plugin/containers/jvm-container/src/main/docker/run.sh
  test/plugin/containers/tomcat-container/pom.xml
  test/plugin/run.sh
Labels: docker, testing

#380 correct toolkit naming
  CHANGES.md
  apm-sniffer/config/agent.config
  docs/en/setup/service-agent/java-agent/configurations.md
Labels: bug

#381 Rename`JDBI` to `JDBC`
  .github/workflows/plugins-test.3.yaml
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/clickhouse-0.3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/clickhouse/ClickHouseStatementTracingWrapper.java
  apm-sniffer/apm-sdk-plugin/impala-jdbc-2.6.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/impala/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/impala-jdbc-2.6.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/impala/StatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/impala-jdbc-2.6.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/impala/PreparedStatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/impala-jdbc-2.6.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/impala/StatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/ConnectionServiceMethodInterceptor.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/trace/CallableStatementTracing.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/trace/PreparedStatementTracing.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/trace/StatementTracing.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/test/java/org/apache/skywalking/apm/plugin/jdbc/ConnectionTracing.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/test/java/org/apache/skywalking/apm/plugin/jdbc/SWCallableStatementTest.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/test/java/org/apache/skywalking/apm/plugin/jdbc/SWConnectionTest.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/test/java/org/apache/skywalking/apm/plugin/jdbc/SWStatementTest.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/test/java/org/apache/skywalking/apm/plugin/jdbc/SwPreparedStatementTest.java
  apm-sniffer/apm-sdk-plugin/kylin-jdbc-2.6.x-3.x-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/kylin/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/kylin-jdbc-2.6.x-3.x-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/kylin/StatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/kylin-jdbc-2.6.x-3.x-4.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/kylin/PreparedStatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/kylin-jdbc-2.6.x-3.x-4.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/kylin/StatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/mariadb-2.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/mariadb/v2/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mariadb-2.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/mariadb/v2/StatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mariadb-2.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/mariadb/v2/PreparedStatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/mariadb-2.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/mariadb/v2/StatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/mssql-commons/src/main/java/org/apache/skywalking/apm/plugin/mssql/commons/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mssql-commons/src/main/java/org/apache/skywalking/apm/plugin/mssql/commons/StatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mysql-common/src/main/java/org/apache/skywalking/apm/plugin/jdbc/mysql/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mysql-common/src/main/java/org/apache/skywalking/apm/plugin/jdbc/mysql/StatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mysql-common/src/test/java/org/apache/skywalking/apm/plugin/jdbc/mysql/StatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/postgresql-8.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/postgresql/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/postgresql-8.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/postgresql/StatementExecuteMethodsInterceptor.java
  test/plugin/scenarios/clickhouse-0.3.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/dbcp-2.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/druid-1.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/h2-scenario/config/expectedData.yaml
  test/plugin/scenarios/hikaricp-scenario/config/expectedData.yaml
  test/plugin/scenarios/impala-jdbc-2.6.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/kotlin-coroutine-scenario/config/expectedData.yaml
  test/plugin/scenarios/kylin-jdbc-2.6.x-3.x-4.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/mariadb-scenario/config/expectedData.yaml
  test/plugin/scenarios/mssql-jdbc-scenario/config/expectedData.yaml
  test/plugin/scenarios/mssql-jtds-scenario/config/expectedData.yaml
  test/plugin/scenarios/mybatis-3.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/mysql-scenario/config/expectedData.yaml
  test/plugin/scenarios/oracle-scenario/config/expectedData.yaml
  test/plugin/scenarios/postgresql-above9.4.1207-scenario/config/expectedData.yaml
  test/plugin/scenarios/postgresql-scenario/config/expectedData.yaml
  test/plugin/scenarios/shardingsphere-3.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/shardingsphere-4.0.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/shardingsphere-4.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/shardingsphere-5.0.0-scenario/config/expectedData.yaml
  test/plugin/scenarios/spring-tx-scenario/config/expectedData.yaml
  test/plugin/scenarios/springmvc-reactive-devtools-scenario/config/expectedData.yaml
  test/plugin/scenarios/springmvc-reactive-scenario/config/expectedData.yaml
Labels: chore, plugin

#383 Update document format in plugin test
  docs/en/setup/service-agent/java-agent/Plugin-test.md
Labels: documentation

#382 Support collecting dubbo thread pool metrics
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/dubbo-2.7.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/asf/dubbo/AbstractServerConstructorInterceptor.java
  apm-sniffer/apm-sdk-plugin/dubbo-2.7.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/asf/dubbo/AbstractServerInstrumentation.java
  apm-sniffer/apm-sdk-plugin/dubbo-2.7.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/apm-sdk-plugin/dubbo-plugin/src/main/java/org/apache/skywalking/apm/plugin/dubbo/AbstractServerConstructorInterceptor.java
  apm-sniffer/apm-sdk-plugin/dubbo-plugin/src/main/java/org/apache/skywalking/apm/plugin/dubbo/AbstractServerInstrumentation.java
  apm-sniffer/apm-sdk-plugin/dubbo-plugin/src/main/resources/skywalking-plugin.def
  docs/en/setup/service-agent/java-agent/Plugin-list.md
  docs/en/setup/service-agent/java-agent/Supported-list.md
  test/plugin/scenarios/dubbo-2.5.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/dubbo-2.5.x-scenario/configuration.yml
  test/plugin/scenarios/dubbo-2.5.x-scenario/src/main/java/org/apache/skywalking/apm/testcase/dubbo/Application.java
  test/plugin/scenarios/dubbo-2.7.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/dubbo-2.7.x-scenario/configuration.yml
  test/plugin/scenarios/dubbo-2.7.x-scenario/src/main/java/org/apache/skywalking/apm/testcase/dubbo/Application.java
Labels: plugin, feature

#388 Bump up byte-buddy to 1.12.19
  CHANGES.md
  dist-material/LICENSE
  pom.xml
Labels: dependency

#387 Upgrade agent-test-tools and polish dubbo plugin
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/dubbo-2.7.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/asf/dubbo/AbstractServerConstructorInterceptor.java
  apm-sniffer/apm-sdk-plugin/dubbo-plugin/src/main/java/org/apache/skywalking/apm/plugin/dubbo/AbstractServerConstructorInterceptor.java
  docs/en/setup/service-agent/java-agent/Plugin-test.md
  test/plugin/agent-test-tools/pom.xml
  tools/plugin/check-javaagent-plugin-list.sh
Labels: enhancement, plugin

#389 Compatible with 3.x and 4.x RabbitMQ Client
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/rabbitmq-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/rabbitmq-plugin/src/main/java/org/apache/skywalking/apm/plugin/rabbitmq/ChannelNConstructorInterceptor.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-plugin/src/main/java/org/apache/skywalking/apm/plugin/rabbitmq/RabbitMQConsumerInterceptor.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-plugin/src/main/java/org/apache/skywalking/apm/plugin/rabbitmq/RabbitMQProducerInterceptor.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-plugin/src/main/java/org/apache/skywalking/apm/plugin/rabbitmq/TracerConsumer.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-plugin/src/main/java/org/apache/skywalking/apm/plugin/rabbitmq/define/ChannelNInstrumentation.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/apm-sdk-plugin/rabbitmq-plugin/src/test/java/org/apache/skywalking/apm/plugin/rabbitmq/ChannelNConstructorInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-plugin/src/test/java/org/apache/skywalking/apm/plugin/rabbitmq/RabbitMQConsumerInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-plugin/src/test/java/org/apache/skywalking/apm/plugin/rabbitmq/RabbitMQProducerInterceptorTest.java
  docs/en/setup/service-agent/java-agent/Plugin-list.md
  docs/en/setup/service-agent/java-agent/Supported-list.md
  test/plugin/scenarios/rabbitmq-scenario/src/main/java/org/apache/skywalking/apm/testcase/rabbitmq/controller/CaseController.java
  test/plugin/scenarios/rabbitmq-scenario/support-version.list
Labels: enhancement, plugin

#392 Print meter size when it exceeds the maximum value
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/meter/MeterService.java
Labels: chore

#396 Polish JDBC plugins to make DBType accurate
  .github/workflows/plugins-test.3.yaml
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/clickhouse-0.3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/clickhouse/ClickHouseStatementTracingWrapper.java
  apm-sniffer/apm-sdk-plugin/clickhouse-0.3.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/clickhouse/ClickHouseStatementMethodInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/impala-jdbc-2.6.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/impala/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/impala-jdbc-2.6.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/impala/StatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/impala-jdbc-2.6.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/impala/PreparedStatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/impala-jdbc-2.6.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/impala/StatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/ConnectionServiceMethodInterceptor.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/trace/CallableStatementTracing.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/trace/PreparedStatementTracing.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/trace/StatementTracing.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/test/java/org/apache/skywalking/apm/plugin/jdbc/AbstractStatementTest.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/test/java/org/apache/skywalking/apm/plugin/jdbc/ConnectionTracing.java
  apm-sniffer/apm-sdk-plugin/kylin-jdbc-2.6.x-3.x-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/kylin/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/kylin-jdbc-2.6.x-3.x-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/kylin/StatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/kylin-jdbc-2.6.x-3.x-4.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/kylin/PreparedStatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/kylin-jdbc-2.6.x-3.x-4.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/kylin/StatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/mariadb-2.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/mariadb/v2/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mariadb-2.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/mariadb/v2/StatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mariadb-2.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/mariadb/v2/PreparedStatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/mariadb-2.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/jdbc/mariadb/v2/StatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/mssql-commons/src/main/java/org/apache/skywalking/apm/plugin/mssql/commons/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mssql-commons/src/main/java/org/apache/skywalking/apm/plugin/mssql/commons/StatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mysql-common/src/main/java/org/apache/skywalking/apm/plugin/jdbc/mysql/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mysql-common/src/main/java/org/apache/skywalking/apm/plugin/jdbc/mysql/StatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/mysql-common/src/test/java/org/apache/skywalking/apm/plugin/jdbc/mysql/StatementExecuteMethodsInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/postgresql-8.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/postgresql/PreparedStatementExecuteMethodsInterceptor.java
  apm-sniffer/apm-sdk-plugin/postgresql-8.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/jdbc/postgresql/StatementExecuteMethodsInterceptor.java
  test/plugin/scenarios/clickhouse-0.3.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/dbcp-2.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/druid-1.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/h2-scenario/config/expectedData.yaml
  test/plugin/scenarios/hikaricp-scenario/config/expectedData.yaml
  test/plugin/scenarios/impala-jdbc-2.6.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/kotlin-coroutine-scenario/config/expectedData.yaml
  test/plugin/scenarios/kylin-jdbc-2.6.x-3.x-4.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/mariadb-scenario/config/expectedData.yaml
  test/plugin/scenarios/mssql-jdbc-scenario/config/expectedData.yaml
  test/plugin/scenarios/mssql-jtds-scenario/config/expectedData.yaml
  test/plugin/scenarios/mybatis-3.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/mysql-scenario/config/expectedData.yaml
  test/plugin/scenarios/oracle-scenario/config/expectedData.yaml
  test/plugin/scenarios/postgresql-above9.4.1207-scenario/config/expectedData.yaml
  test/plugin/scenarios/postgresql-scenario/config/expectedData.yaml
  test/plugin/scenarios/shardingsphere-3.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/shardingsphere-4.0.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/shardingsphere-4.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/shardingsphere-5.0.0-scenario/config/expectedData.yaml
  test/plugin/scenarios/spring-tx-scenario/config/expectedData.yaml
Labels: enhancement

#398 Bump up markdown-link-check. Ignore 127.0.0.1
  .dlc.json
  .github/workflows/dead-link-checker.yaml
Labels: CI Setting

#399 Fix undertow-worker-thread-pool-scenario didn't lock Spring boot version.
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/configuration.yml
  test/plugin/scenarios/undertow-worker-thread-pool-scenario/pom.xml
Labels: testing

#397 Report the agent version to OAP
  CHANGES.md
  apm-sniffer/apm-agent-core/pom.xml
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/util/InstanceJsonPropertiesUtil.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/version/Version.java
  pom.xml
  test/e2e/case/expected/service-instance.yml
  tools/releasing/create_release.sh
Labels: enhancement
