Repository apache/skywalking-java, pull requests merged in 2022-10, with the labels that each got.

#346 docs: correct spelling
  docs/en/setup/service-agent/java-agent/Supported-list.md
Labels: chore

#348 Update `compose-start-script.template` to make compatible with new version docker compose
  CHANGES.md
  test/plugin/runner-helper/src/main/resources/compose-start-script.template
Labels: enhancement, testing

#349 Fix dead link
  .dlc.json
  docs/en/setup/service-agent/java-agent/Supported-list.md
Labels: documentation

#350 Bump up grpc to 1.50.0 to fix CVE-2022-3171
  CHANGES.md
  dist-material/LICENSE
  pom.xml
Labels: dependency

#353 Correct the duration of the transaction span for Neo4J 4.x
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/neo4j-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/neo4j/v4x/TransactionRunInterceptor.java
Labels: bug, plugin

#357 Plugin-test configuration.yml dependencies support docker service command field
  CHANGES.md
  docs/en/setup/service-agent/java-agent/Plugin-test.md
  test/plugin/runner-helper/src/main/java/org/apache/skywalking/plugin/test/helper/ConfigurationImpl.java
  test/plugin/runner-helper/src/main/java/org/apache/skywalking/plugin/test/helper/vo/DependencyComponent.java
  test/plugin/runner-helper/src/main/java/org/apache/skywalking/plugin/test/helper/vo/DockerService.java
  test/plugin/runner-helper/src/main/resources/docker-compose.template
Labels: testing

#362 Polish up rabbitmq-5.x plugin to fix missing broker tag on consumer side
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/rabbitmq-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rabbitmq/ChannelNConstructorInterceptor.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rabbitmq/RabbitMQConsumerInterceptor.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rabbitmq/TracerConsumer.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rabbitmq/define/ChannelNInstrumentation.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/rabbitmq/define/RabbitMQProducerInstrumentation.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-5.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/apm-sdk-plugin/rabbitmq-5.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/rabbitmq/ChannelNConstructorInterceptorTest.java
  apm-sniffer/apm-sdk-plugin/rabbitmq-5.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/rabbitmq/RabbitMQConsumerInterceptorTest.java
Labels: enhancement, plugin

#363 Polish up activemq plugin to fix missing broker tag on consumer side
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/activemq-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/activemq/MessageConsumerDequeueInterceptor.java
  apm-sniffer/apm-sdk-plugin/activemq-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/activemq/define/ActiveMQConsumerInstrumentation.java
  apm-sniffer/apm-sdk-plugin/activemq-5.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/activemq/MessageConsumerDequeueInterceptorTest.java
  docs/en/setup/service-agent/java-agent/Plugin-test.md
  test/plugin/agent-test-tools/pom.xml
  test/plugin/scenarios/activemq-scenario/config/expectedData.yaml
  test/plugin/scenarios/kafka-scenario/config/expectedData.yaml
  test/plugin/scenarios/nats-2.14.x-2.15.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/rabbitmq-scenario/config/expectedData.yaml
Labels: enhancement, plugin, testing

#361 Add rocketmq plugin test scenarios
  .github/workflows/plugins-test.2.yaml
  CHANGES.md
  test/plugin/containers/jvm-container/src/main/docker/run.sh
  test/plugin/scenarios/rocketmq-scenario/bin/startup.sh
  test/plugin/scenarios/rocketmq-scenario/config/expectedData.yaml
  test/plugin/scenarios/rocketmq-scenario/configuration.yml
  test/plugin/scenarios/rocketmq-scenario/pom.xml
  test/plugin/scenarios/rocketmq-scenario/src/main/assembly/assembly.xml
  test/plugin/scenarios/rocketmq-scenario/src/main/java/test/apache/skywalking/apm/testcase/rocketmq/Application.java
  test/plugin/scenarios/rocketmq-scenario/src/main/java/test/apache/skywalking/apm/testcase/rocketmq/controller/CaseController.java
  test/plugin/scenarios/rocketmq-scenario/src/main/resources/application.yaml
  test/plugin/scenarios/rocketmq-scenario/src/main/resources/log4j2.xml
  test/plugin/scenarios/rocketmq-scenario/support-version.list
Labels: plugin, testing

#370 Mention Virtual Cache support in the changelog
  CHANGES.md
Labels: chore
