Repository apache/skywalking-java, pull requests merged in 2023-01, with the labels that each got.

#436 [Deadlock] Move `Agent-Version` property reading away from the class loading stage
  CHANGES.md
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/remote/AgentIDDecorator.java
Labels: bug, core

#437 Put `Agent-Version` property reading in premain stage to avoid deadlock when use `jarsigner`.
  CHANGES.md
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/Config.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/SnifferConfigInitializer.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/remote/AgentIDDecorator.java
Labels: bug, chore

#439 Add a config `agent.enable`(default: true) to support disabling agent
  CHANGES.md
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/Config.java
  apm-sniffer/apm-agent/src/main/java/org/apache/skywalking/apm/agent/SkyWalkingAgent.java
  apm-sniffer/config/agent.config
  docs/en/setup/service-agent/java-agent/configurations.md
Labels: enhancement

#438 Enhance redisson plugin to adopt uniform tags
  CHANGES.md
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/tag/Tags.java
  apm-sniffer/apm-sdk-plugin/redisson-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/redisson/v3/RedisConnectionMethodInterceptor.java
  apm-sniffer/apm-sdk-plugin/redisson-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/redisson/v3/RedissonPluginConfig.java
  apm-sniffer/config/agent.config
  docs/en/setup/service-agent/java-agent/configurations.md
  test/plugin/scenarios/redisson-scenario/config/expectedData.yaml
Labels: enhancement, plugin

#441 Enhance lettuce plugin to adopt uniform tags
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/lettuce-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/lettuce/v5/LettucePluginConfig.java
  apm-sniffer/apm-sdk-plugin/lettuce-5.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/lettuce/v5/RedisChannelWriterInterceptor.java
  apm-sniffer/apm-sdk-plugin/lettuce-5.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/lettuce/v5/RedisChannelWriterInterceptorTest.java
  apm-sniffer/config/agent.config
  docs/en/setup/service-agent/java-agent/configurations.md
  test/plugin/scenarios/lettuce-scenario/config/expectedData.yaml
Labels: enhancement, plugin

#443 Uncommented Mircometer Observation CI test
  .github/workflows/plugins-jdk17-test.0.yaml
  test/plugin/scenarios/resttemplate-6.x-scenario/pom.xml
Labels: testing

#446 Fix wrong JDK version when publish Docker snapshot
  .github/workflows/publish-docker.yaml
Labels: CI Setting
