Repository apache/skywalking-java, pull requests merged in 2023-10, with the labels that each got.

#618 Add mongoDB plugin report db instance info
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/AggregateExplainOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/AggregateOperationImplInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/AggregateOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/ChangeStreamOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/CommandReadOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/CountOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/DistinctOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/FindOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/ListCollectionsOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/ListIndexesOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/MapReduceWithInlineResultsOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/readOperation/WrappedMapReduceReadOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/AggregateToCollectionOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/BaseFindAndModifyOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/BaseWriteOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/CommandWriteOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/CreateCollectionOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/CreateIndexesOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/CreateViewOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/DropCollectionOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/DropDatabaseOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/DropIndexOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/MapReduceToCollectionOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/MixedBulkWriteOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/define/writeOperation/RenameCollectionOperationInstrumentation.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/interceptor/operation/OperationDatabaseConstructInterceptor.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/interceptor/operation/OperationNamespaceConstructInterceptor.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/interceptor/operation/WrappedMapReduceReadOperationInterceptor.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/mongodb/v4/support/MongoSpanHelper.java
  apm-sniffer/apm-sdk-plugin/mongodb-4.x-plugin/src/main/resources/skywalking-plugin.def
  test/plugin/scenarios/mongodb-4.x-scenario/config/expectedData.yaml
Labels: enhancement, plugin

#621 Fix oracle lower case tns url parse error. (#11399)
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/main/java/org/apache/skywalking/apm/plugin/jdbc/connectionurl/parser/OracleURLParser.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/test/java/org/apache/skywalking/apm/plugin/jdbc/connectionurl/parser/URLParserTest.java
Labels: enhancement

#623 Fix config length limitation.
  CHANGES.md
  apm-commons/apm-util/src/main/java/org/apache/skywalking/apm/util/ConfigInitializer.java
Labels: bug

#624 Add OAP version requirement
  docs/en/setup/service-agent/java-agent/README.md
Labels: documentation

#626 [DOCS] Corrected an issue using misspelled words in Native Tracer
  docs/en/setup/service-agent/java-agent/Application-toolkit-tracer.md
Labels: documentation

#632 Fix CVE-2023-4586
  CHANGES.md
  dist-material/LICENSE
  pom.xml
Labels: dependency

#625 Add a netty-4.1.x plugin to trace http
  .github/workflows/plugins-test.1.yaml
  CHANGES.md
  apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/ComponentsDefine.java
  apm-sniffer/config/agent.config
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/pom.xml
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/AddHttpRequestDecoderInterceptor.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/AddHttpRequestEncoderInterceptor.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/AddHttpResponseDecoderInterceptor.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/AddHttpResponseEncoderInterceptor.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/ChannelHandlerContextInterceptor.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/ChannelPipelineRemoveLastInterceptor.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/RemoveHandlerInterceptor.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/common/AttributeKeys.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/common/NettyConstants.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/config/NettyHttpPluginConfig.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/define/AbstractNettyInstrumentation.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/define/ChannelHandlerContextInstrumentation.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/define/ChannelHandlerInstrumentation.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/define/ChannelPipelineInstrumentation.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/define/HttpRequestDecoderInstrumentation.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/define/HttpRequestEncoderInstrumentation.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/define/HttpResponseDecoderInstrumentation.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/define/HttpResponseEncoderInstrumentation.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/handler/NettyHttpRequestDecoderTracingHandler.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/handler/NettyHttpRequestEncoderTracingHandler.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/handler/NettyHttpResponseDecoderTracingHandler.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/handler/NettyHttpResponseEncoderTracingHandler.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/utils/HttpDataCollectUtils.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/netty/http/utils/TypeUtils.java
  apm-sniffer/optional-plugins/netty-http-4.1.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/optional-plugins/pom.xml
  docs/en/setup/service-agent/java-agent/Optional-plugins.md
  docs/en/setup/service-agent/java-agent/Plugin-list.md
  docs/en/setup/service-agent/java-agent/Supported-list.md
  docs/en/setup/service-agent/java-agent/configurations.md
  test/plugin/scenarios/netty-http-4.1.x-scenario/bin/startup.sh
  test/plugin/scenarios/netty-http-4.1.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/netty-http-4.1.x-scenario/configuration.yml
  test/plugin/scenarios/netty-http-4.1.x-scenario/pom.xml
  test/plugin/scenarios/netty-http-4.1.x-scenario/src/main/assembly/assembly.xml
  test/plugin/scenarios/netty-http-4.1.x-scenario/src/main/java/test/apache/skywalking/apm/testcase/netty/http/Application.java
  test/plugin/scenarios/netty-http-4.1.x-scenario/src/main/java/test/apache/skywalking/apm/testcase/netty/http/controller/CaseController.java
  test/plugin/scenarios/netty-http-4.1.x-scenario/src/main/java/test/apache/skywalking/apm/testcase/netty/http/core/ClientService.java
  test/plugin/scenarios/netty-http-4.1.x-scenario/src/main/java/test/apache/skywalking/apm/testcase/netty/http/core/ServerService.java
  test/plugin/scenarios/netty-http-4.1.x-scenario/src/main/java/test/apache/skywalking/apm/testcase/netty/http/handler/UserClientHandler.java
  test/plugin/scenarios/netty-http-4.1.x-scenario/src/main/java/test/apache/skywalking/apm/testcase/netty/http/handler/UserServerHandler.java
  test/plugin/scenarios/netty-http-4.1.x-scenario/src/main/resources/application.yaml
  test/plugin/scenarios/netty-http-4.1.x-scenario/support-version.list
Labels: plugin, feature

#641 Disable dep bot
  .asf.yaml
Labels: dependency
