Repository apache/skywalking-java, pull requests merged in 2024-11, with the labels that each got.

#727 fix: shade async-profiler packages
  apm-sniffer/apm-agent-core/pom.xml
  apm-sniffer/apm-agent/pom.xml
Labels: bug

#729 Fix deadlinks
  .dlc.json
  docs/en/setup/service-agent/java-agent/Java-Plugin-Development-Guide.md
Labels: chore

#730 Improve CustomizeConfiguration by avoiding repeatedly resolve file config
  CHANGES.md
  apm-sniffer/optional-plugins/customize-enhance-plugin/src/main/java/org/apache/skywalking/apm/plugin/customize/conf/CustomizeConfiguration.java
Labels: enhancement

#732 Add empty judgment for constructorInterceptPoint
  CHANGES.md
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/interceptor/enhance/ClassEnhancePluginDefine.java
Labels: enhancement
