Repository apache/skywalking-java, pull requests merged in 2024-12, with the labels that each got.

#733 fix: async profiler max duration && reduce memory allocation when sending jfr
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/asyncprofiler/AsyncProfilerDataSender.java
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/conf/Config.java
  apm-sniffer/config/agent.config
Labels: enhancement

#734 fix: rm tomcat-10x-plugin version
  apm-sniffer/apm-sdk-plugin/tomcat-10x-plugin/pom.xml
Labels: bug, chore

#735 Bump up actions/cache to v4
  .github/actions/build/action.yml
  .github/actions/run/action.yml
  .github/workflows/ci.yaml
  .github/workflows/publish-docker.yaml
Labels: CI Setting

#737 Bump up gRPC and netty versions
  CHANGES.md
  apm-protocol/apm-network/pom.xml
  dist-material/LICENSE
  pom.xml
Labels: dependency

#739 Fix CreateAopProxyInterceptor in the Spring core-patch indeed changes the implementation of the Spring AOP proxy
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/spring-plugins/core-patch/src/main/java/org/apache/skywalking/apm/plugin/spring/patch/CreateAopProxyInterceptor.java
  apm-sniffer/apm-sdk-plugin/spring-plugins/core-patch/src/test/java/org/apache/skywalking/apm/plugin/spring/patch/CreateAopProxyInterceptorTest.java
Labels: bug

#736 [Feature] Support Tracing for GlobalFilter and GatewayFilter in Gateway
  CHANGES.md
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-2.0.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v20x/GatewayFilterInterceptor.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-2.0.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v20x/define/Constants.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-2.0.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v20x/define/GatewayFilterInstrumentation.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-2.0.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-2.0.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v20x/GatewayFilterInterceptorTest.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-2.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v21x/GatewayFilterInterceptor.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-2.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v21x/define/Constants.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-2.1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v21x/define/GatewayFilterInstrumentation.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-2.1.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-2.1.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v21x/GatewayFilterInterceptorTest.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v3x/GatewayFilterInterceptor.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v3x/define/GatewayFilterInstrumentation.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-3.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-3.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v3x/GatewayFilterInterceptorTest.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v4x/GatewayFilterInterceptor.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-4.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v4x/define/GatewayFilterInstrumentation.java
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-4.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/gateway-4.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/spring/cloud/gateway/v4x/GatewayFilterInterceptorTest.java
  test/plugin/scenarios/gateway-2.0.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/gateway-2.1.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/gateway-3.x-filter-context-scenario/config/expectedData.yaml
  test/plugin/scenarios/gateway-3.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/gateway-4.x-scenario/config/expectedData.yaml
Labels: enhancement, plugin

#740 Enhance optional plugin docs for Spring Gateway.
  CHANGES.md
  docs/en/setup/service-agent/java-agent/Optional-plugins.md
  docs/en/setup/service-agent/java-agent/agent-optional-plugins/Oracle-Resin-plugins.md
  docs/en/setup/service-agent/java-agent/agent-optional-plugins/Spring-annotation-plugin.md
  docs/en/setup/service-agent/java-agent/agent-optional-plugins/spring-gateway.md
  docs/en/setup/service-agent/java-agent/agent-optional-plugins/trace-ignore-plugin.md
  docs/menu.yml
Labels: documentation

#741 Enhance gRPC server side async support.
  CHANGES.md
  apm-sniffer/apm-sdk-plugin/grpc-1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/grpc/v1/server/ServerInterceptor.java
  apm-sniffer/apm-sdk-plugin/grpc-1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/grpc/v1/server/TracingServerCall.java
  apm-sniffer/apm-sdk-plugin/grpc-1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/grpc/v1/server/TracingServerCallListener.java
Labels: enhancement, plugin

#742 Polish codes
  apm-sniffer/apm-sdk-plugin/grpc-1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/grpc/v1/server/ServerInterceptor.java
Labels: chore

#743 Add Caffeine plugin as optional
  .github/workflows/ci.yaml
  .github/workflows/codeql.yaml
  .github/workflows/plugins-jdk17-test.1.yaml
  CHANGES.md
  apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/ComponentsDefine.java
  apm-sniffer/config/agent.config
  apm-sniffer/optional-plugins/caffeine-3.x-plugin/pom.xml
  apm-sniffer/optional-plugins/caffeine-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/caffeine/v3/AbstractCaffeineInterceptor.java
  apm-sniffer/optional-plugins/caffeine-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/caffeine/v3/CaffeineIterableInterceptor.java
  apm-sniffer/optional-plugins/caffeine-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/caffeine/v3/CaffeineMapInterceptor.java
  apm-sniffer/optional-plugins/caffeine-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/caffeine/v3/CaffeineOperationTransform.java
  apm-sniffer/optional-plugins/caffeine-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/caffeine/v3/CaffeinePluginConfig.java
  apm-sniffer/optional-plugins/caffeine-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/caffeine/v3/CaffeineStringInterceptor.java
  apm-sniffer/optional-plugins/caffeine-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/caffeine/v3/define/CaffeineInstrumentation.java
  apm-sniffer/optional-plugins/caffeine-3.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/optional-plugins/caffeine-3.x-plugin/src/test/java/org/apache/skywalking/apm/plugin/caffeine/v3/CaffeineInterceptorTest.java
  apm-sniffer/optional-plugins/caffeine-3.x-plugin/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  apm-sniffer/optional-plugins/pom.xml
  docs/en/setup/service-agent/java-agent/Plugin-list.md
  docs/en/setup/service-agent/java-agent/Supported-list.md
  docs/en/setup/service-agent/java-agent/configurations.md
  test/plugin/scenarios/caffeine-3.x-scenario/bin/startup.sh
  test/plugin/scenarios/caffeine-3.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/caffeine-3.x-scenario/configuration.yml
  test/plugin/scenarios/caffeine-3.x-scenario/pom.xml
  test/plugin/scenarios/caffeine-3.x-scenario/src/main/assembly/assembly.xml
  test/plugin/scenarios/caffeine-3.x-scenario/src/main/java/org/apache/skywalking/apm/testcase/caffeine/Application.java
  test/plugin/scenarios/caffeine-3.x-scenario/src/main/java/org/apache/skywalking/apm/testcase/caffeine/controller/CaffeineController.java
  test/plugin/scenarios/caffeine-3.x-scenario/src/main/java/org/apache/skywalking/apm/testcase/caffeine/controller/HeartbeatController.java
  test/plugin/scenarios/caffeine-3.x-scenario/src/main/resources/application.yaml
  test/plugin/scenarios/caffeine-3.x-scenario/support-version.list
Labels: plugin
