Repository apache/skywalking-java, pull requests merged in 2024-06, with the labels that each got.

#695 Fix to Ensure All Rules Satisfy not isInterface
  CHANGES.md
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/plugin/PluginFinder.java
Labels: bug

#696 Fix the opentracing toolkit SPI config
  CHANGES.md
  apm-application-toolkit/apm-toolkit-opentracing/src/main/resources/META-INF/services/io.opentracing.Tracer
Labels: bug

#699 Remove Oracle scenario from testing.
  .github/workflows/plugins-test.3.yaml
  test/plugin/scenarios/oracle-scenario/bin/startup.sh
  test/plugin/scenarios/oracle-scenario/config/expectedData.yaml
  test/plugin/scenarios/oracle-scenario/configuration.yml
  test/plugin/scenarios/oracle-scenario/pom.xml
  test/plugin/scenarios/oracle-scenario/src/main/assembly/assembly.xml
  test/plugin/scenarios/oracle-scenario/src/main/java/org/apache/skywalking/apm/testcase/oracle/Application.java
  test/plugin/scenarios/oracle-scenario/src/main/java/org/apache/skywalking/apm/testcase/oracle/controller/CaseController.java
  test/plugin/scenarios/oracle-scenario/src/main/resources/application.yaml
  test/plugin/scenarios/oracle-scenario/src/main/resources/log4j2.xml
  test/plugin/scenarios/oracle-scenario/support-version.list
Labels: testing

#698 Improve 4x performance of ContextManagerExtendService.createTraceCont…
  CHANGES.md
  apm-sniffer/apm-agent-core/pom.xml
  apm-sniffer/apm-agent-core/src/main/java/org/apache/skywalking/apm/agent/core/context/ContextManagerExtendService.java
  apm-sniffer/apm-agent-core/src/test/java/org/apache/skywalking/apm/agent/core/context/IgnoreSuffixBenchmark.java
Labels: enhancement, core

#700 Fix problem which lead redisson plugin to throw unnecessary NullPointerException
  apm-sniffer/apm-sdk-plugin/redisson-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/redisson/v3/RedisConnectionMethodInterceptor.java
  apm-sniffer/apm-sdk-plugin/redisson-3.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/redisson/v3/define/RedisConnectionInstrumentation.java
Labels: bug, plugin

#701 Fix RESTEasy link 404
  docs/en/setup/service-agent/java-agent/Supported-list.md
Labels: chore

#697 Add a plugin that supports the Solon framework.
  .github/workflows/plugins-test.3.yaml
  CHANGES.md
  apm-protocol/apm-network/src/main/java/org/apache/skywalking/apm/network/trace/component/ComponentsDefine.java
  apm-sniffer/apm-sdk-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/solon-2.x-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/solon-2.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/solon/SolonActionExecuteInterceptor.java
  apm-sniffer/apm-sdk-plugin/solon-2.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/solon/SolonPluginConfig.java
  apm-sniffer/apm-sdk-plugin/solon-2.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/solon/define/SolonActionInstrumentation.java
  apm-sniffer/apm-sdk-plugin/solon-2.x-plugin/src/main/resources/skywalking-plugin.def
  apm-sniffer/config/agent.config
  docs/en/setup/service-agent/java-agent/Plugin-list.md
  docs/en/setup/service-agent/java-agent/Supported-list.md
  docs/en/setup/service-agent/java-agent/configurations.md
  test/plugin/scenarios/solon-2.x-scenario/bin/startup.sh
  test/plugin/scenarios/solon-2.x-scenario/config/expectedData.yaml
  test/plugin/scenarios/solon-2.x-scenario/configuration.yml
  test/plugin/scenarios/solon-2.x-scenario/pom.xml
  test/plugin/scenarios/solon-2.x-scenario/src/main/assembly/assembly.xml
  test/plugin/scenarios/solon-2.x-scenario/src/main/java/test/apache/skywalking/apm/testcase/sc/solon/App.java
  test/plugin/scenarios/solon-2.x-scenario/src/main/java/test/apache/skywalking/apm/testcase/sc/solon/controller/Controller.java
  test/plugin/scenarios/solon-2.x-scenario/src/main/java/test/apache/skywalking/apm/testcase/sc/solon/service/TestService.java
  test/plugin/scenarios/solon-2.x-scenario/src/main/resources/app.yml
  test/plugin/scenarios/solon-2.x-scenario/support-version.list
Labels: plugin, feature
