Repository apache/skywalking-java, pull requests merged in 2025-01, with the labels that each got.

#746 modify `plugin.dest.dir` property
  apm-sniffer/apm-sdk-plugin/apm-armeria-plugins/pom.xml
  apm-sniffer/apm-sdk-plugin/graphql-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/hutool-plugins/pom.xml
  apm-sniffer/apm-sdk-plugin/jedis-plugins/pom.xml
  apm-sniffer/apm-sdk-plugin/jetty-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/light4j-plugins/pom.xml
  apm-sniffer/apm-sdk-plugin/micronaut-plugins/pom.xml
  apm-sniffer/apm-sdk-plugin/nutz-plugins/pom.xml
  apm-sniffer/apm-sdk-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/resteasy-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/servicecomb-plugin/pom.xml
  apm-sniffer/apm-sdk-plugin/shardingsphere-plugins/pom.xml
  apm-sniffer/apm-sdk-plugin/spring-plugins/pom.xml
  apm-sniffer/apm-sdk-plugin/spring-plugins/spring-cloud/netflix-plugins/pom.xml
  apm-sniffer/apm-sdk-plugin/spring-plugins/spring-cloud/pom.xml
  apm-sniffer/apm-sdk-plugin/undertow-plugins/pom.xml
  apm-sniffer/apm-sdk-plugin/vertx-plugins/pom.xml
  apm-sniffer/bootstrap-plugins/pom.xml
  apm-sniffer/expired-plugins/pom.xml
  apm-sniffer/optional-plugins/optional-spring-plugins/optional-spring-cloud/pom.xml
  apm-sniffer/optional-plugins/optional-spring-plugins/pom.xml
  apm-sniffer/optional-plugins/pom.xml
  apm-sniffer/optional-reporter-plugins/pom.xml
Labels: enhancement

#748 Fix ConsumeDriver running status
  CHANGES.md
  apm-commons/apm-datacarrier/src/main/java/org/apache/skywalking/apm/commons/datacarrier/consumer/ConsumeDriver.java
Labels: bug

#749 Update URLParserTest.java
  apm-sniffer/apm-sdk-plugin/jdbc-commons/src/test/java/org/apache/skywalking/apm/plugin/jdbc/connectionurl/parser/URLParserTest.java
Labels: chore, testing
